apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Providence-ops/GitOps-Example.git
    targetRevision: main
    path: helm-chart/my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx  # Must match the namespace where you want it deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
